#!/bin/bash

describe_command ()
{
    echo "Enable a module."
}


describe_command_options ()
{
    qd_describe_command_option "name" "string" "The module name." true
}


run_command ()
{
    local config_dir=/etc/nginx
    local name=$QDC_NAME
    local file=$config_dir/modules-available/$name.conf

    [ -f "$file" ] || qd_error "The module '$name' is not defined."

    qd_link "$file" "$config_dir/modules-enabled/" true
}
