#!/bin/bash

describe_command ()
{
    echo "Disable a site."
}


describe_command_options ()
{
    qd_describe_command_option "name" "string" "The site name." true
    qd_describe_command_option "prefix" "string" "The directory prefix." true "$QDS_NGINX_PREFIX"
}


run_command ()
{
    local name=$QDC_NAME
    local file=$QDC_PREFIX/sites-enabled/$name.conf

    if [ -f $file ]; then
        mv $file $QDC_PREFIX/sites-available/$name.conf
    else
        qd_warn "Site '$name' is not enabled."
    fi
}
