#!/bin/bash

describe_command ()
{
    echo "Disable a module."
}


describe_command_options ()
{
    qd_describe_command_option "name" "string" "The module name." true
    qd_describe_command_option "etc" "string" "The config directory." true "$QDS_NGINX_ETC"
}


run_command ()
{
    local name=$QDC_NAME
    local file=$QDC_ETC/modules-enabled/$name.conf

    if [ -f $file ]; then
        mv $file $QDC_ETC/modules-available/$name.conf
    else
        qd_warn "Module '$name' is not enabled."
    fi
}
