#!/bin/bash

describe_command ()
{
    echo "Enable a module."
}


describe_command_options ()
{
    qd_describe_command_option "name" "string" "The module name." true
    qd_describe_command_option "prefix" "string" "The directory prefix." true "$QDS_NGINX_PREFIX"
}


run_command ()
{
    local name=$QDC_NAME
    local file=$QDC_PREFIX/modules-available/$name.conf

    if [ -f "$file" ]; then
        mv $file $QDC_PREFIX/modules-enabled/$name.conf
    else
        qd_error "Module '$name' is not defined."
    fi
}
