#!/bin/bash

describe_command ()
{
    echo "Start the nginx server."
}


describe_command_options ()
{
    qd_describe_command_option "args" "string" "The nginx command-line arguments." false "$QDS_NGINX_ARGS"
}


run_command ()
{
    nginx -V

    echo

    local name

    for name in $QDS_NGINX_WATCHES
    do
        local ns="nginx.watches.$name"
        local path=$(qd_option "$ns.path")
        local patterns=$(qd_option "$ns.patterns")
        local trigger=$(qd_option "$ns.trigger")

        watchman watch $path
        watchman -- trigger $path "reload-nginx.$name" $patterns -- $trigger
    done


    eval "exec nginx $QDC_ARGS"
}
